application: instant-diorama-690
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /.*
  script: index.app
