application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /philly-concerts
  static_dir: philly-concerts
- url: /.*
  script: index.app
